#ifndef ULTRAVNC_RFB_PROTO_H
#define ULTRAVNC_RFB_PROTO_H

#define KEEPALIVE_HEADROOM 1
#define KEEPALIVE_INTERVAL 5
#define FT_RECV_TIMEOUT    30

// adzm 2010-08
#define SOCKET_KEEPALIVE_TIMEOUT 10000
#define SOCKET_KEEPALIVE_INTERVAL 1000

#endif

