//typedef int vncMenu;

#define MENU_SERVER_SHAREWINDOW 0
#define MENU_PROPERTIES_SHOW 0
#define MENU_DEFAULT_PROPERTIES_SHOW 0
#define MENU_ABOUTBOX_SHOW 0
#define MENU_SERVICEHELPER_MSG 0
#define MENU_RELOAD_MSG 0
#define MENU_ADD_CLIENT_MSG 0
#define MENU_KILL_ALL_CLIENTS_MSG 0
#define MENU_SERVER_SHAREPRIMARY 0
#define MENU_SERVER_SHAREAREA 0
#define MENU_SERVER_SHAREALL 0
