//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by winvnc.rc
//
#define IDI_WINVNC                      102
#define IDD_PROPERTIES                  102
#define IDS_WARNING                     103
#define IDR_TRAYMENU                    104
#define IDR_VNCVIEWER_JAR               116
#define IDR_BLOCKCIPHER_CLASS           120
#define IDR_CIPHER_CLASS                121
#define IDR_CRYPTOUTILS_CLASS           123
#define IDR_IDEACIPHER_CLASS            124
#define IDD_ABOUT                       131
#define IDB_VNCLOGO                     132
#define IDI_FLASH                       134
#define IDD_OUTGOING_CONN               135
#define IDD_ACCEPT_CONN                 136
#define IDD_PATHS                       138
#define IDB_LOGO64                      139
#define IDD_TEXTCHAT_DLG                140
#define IDD_LIST_DLG                    141
#define IDB_BITMAP2                     143
#define IDB_BITMAP4                     144
#define IDB_BITMAP1                     144
#define IDD_MSLOGON                     145
#define IDD_PROPERTIES1                 146
#define IDD_ABOUT1                      147
#define IDR_JAVAARCHIVE1                155
#define IDD_USER_NAME                   604
#define IDD_PASSWORD                    608
#define IDR_MESSAGES_PROPERTIES         900
#define IDR_MESSAGES_CLASS              901
#define IDD_LOGON                       1002
#define IDC_CONNECT_BORDER              1003
#define IDD_AUTH_DIALOG                 1003
#define IDC_CONNECT_SOCK                1004
#define IDC_CONNECT_CORBA               1005
#define IDC_PORTNO_LABEL                1006
#define IDC_CONNECT_HTTP                1006
#define IDC_PASSWORD_LABEL              1007
#define IDC_PORTNO                      1008
#define IDC_DISPLAYNO                   1008
#define IDC_PASSWORD                    1009
#define IDC_PASSWD_EDIT                 1009
#define IDC_UPDATE_BORDER               1010
#define IDC_PASSWORD_LABEL2             1010
#define IDC_POLL_FULLSCREEN             1011
#define IDC_PASSWORD2                   1011
#define IDC_CONSOLE_ONLY                1012
#define IDC_POLL_FOREGROUND             1013
#define IDC_POLL_UNDER_CURSOR           1014
#define IDC_ONEVENT_ONLY                1015
#define IDC_VNCLOGO                     1016
#define IDC_CONNSETTINGS_BORDER         1016
#define IDC_HOSTS                       1016
#define IDC_VERSION                     1017
#define IDC_DISPLAY_NO_LABEL            1017
#define IDC_NAME                        1018
#define IDC_HOST_ADD                    1018
#define IDC_EMAIL                       1019
#define IDC_BUILDTEXT                   1019
#define IDC_HOST_REMOVE                 1019
#define IDC_VNC                         1020
#define IDC_HOST_UP                     1020
#define IDC_ATT                         1021
#define IDC_BUILDTIME                   1021
#define IDC_HOST_DOWN                   1021
#define IDC_WWW                         1022
#define IDC_HOST_EDIT                   1022
#define IDC_COPYRIGHT                   1023
#define IDC_DISABLE_INPUTS              1024
#define IDC_APPLY                       1025
#define IDC_PORTNO_AUTO                 1026
#define IDD_DOMAIN                      1026
#define IDC_HOSTNAME_EDIT               1027
#define IDC_DISABLE_LOCAL_INPUTS        1027
#define IDC_HOSTNAME_STATIC             1028
#define IDC_REMOVE_WALLPAPER            1028
#define IDC_NOTE_STATIC                 1029
#define IDACCEPT                        1030
#define IDREJECT                        1031
#define IDC_STATIC_TEXT1                1032
#define IDC_ACCEPT_IP                   1033
#define IDC_STATIC_TEXT                 1034
#define IDC_ACCEPT_TIMEOUT              1035
#define IDC_TRADEMARK                   1036
#define IDC_AUTO_DISPLAY_NO             1037
#define IDC_MANUAL_DISPLAY_NO           1038
#define IDC_DISPLAY_NUMBER              1039
#define IDC_LOCKSETTINGS                1040
#define IDC_LOCKSETTING_NOTHING         1041
#define IDC_LOCKSETTING_LOGOFF          1042
#define IDC_LOCKSETTING_LOCK            1043
#define IDC_FILETRANSFER                1046
#define IDC_SCALE                       1048
#define IDC_PATH                        1049
#define IDC_SETMASTER                   1050
#define IDC_MSLOGON_CHECK               1051
#define IDC_PLUGIN_CHECK                1052
#define IDC_COMBO1                      1053
#define IDC_PLUGINS_COMBO               1053
#define IDC_PLUGIN_BUTTON               1054
#define IDC_VIEWERS_LISTBOX             1055
#define IDC_SINGLE_WINDOW               1056
#define IDC_CLIENTTEXT                  1056
#define IDC_VIEWERS_LISTBOX2            1056
#define IDC_PENDING_LISTBOX             1056
#define IDC_KILL_B                      1057
#define IDC_NAME_APPLI                  1058
#define IDC_TEXTCHAT_B                  1058
#define IDC_SPECDISPLAY                 1060
#define IDC_SPECPORT                    1061
#define IDC_PORTRFB                     1062
#define IDC_PORTHTTP                    1063
#define IDC_STATUS                      1064
#define IDC_WARNING                     1064
#define IDC_PERSISTENT_CHECK            1065
#define IDC_DRIVER                      1066
#define IDC_HOOK                        1067
#define IDC_VIRTUAL                     1068
#define IDC_CONNECT_XDMCP               1069
#define IDC_BLANK                       1070
#define IDC_BLANK2                      1071
#define IDC_TURBOMODE                   1075
#define IDC_SEND_B                      1078
#define IDC_LOG                         1079
#define IDC_ALLOWLOOPBACK               1080
#define IDQUERY                         1081
#define IDQUERYTIMEOUT                  1082
#define IDC_EDIT1                       1084
#define IDC_GROUP1                      1084
#define IDC_IDCODE                      1084
#define IDC_BLANKINGTXT                 1084
#define IDC_EDIT_PATH                   1084
#define IDC_MAXCPU                      1084
#define IDC_MSLOGON_CHECKD              1085
#define IDC_GROUP2                      1086
#define IDC_MSLOGON_CHECKD2             1086
#define IDC_GROUP3                      1087
#define IDC_CHECKG1L                    1088
#define IDC_CHECKG2L                    1089
#define IDC_CHECKG3L                    1090
#define IDC_CHECKG1D                    1091
#define IDC_CHECKG2D                    1092
#define IDC_CHECKG3D                    1093
#define IDC_MSLOGON                     1094
#define IDC_CHECKDRIVER                 1096
#define IDC_RADIO1                      1097
#define IDC_MV1                         1097
#define IDC_RADIO2                      1098
#define IDC_MV2                         1098
#define IDC_RADIO3                      1099
#define IDC_MV3                         1099
#define IDC_RADIO4                      1100
#define IDC_MV4                         1100
#define IDC_LOOPBACKONLY                1101
#define IDC_CHECK2                      1102
#define IDC_DISABLETRAY                 1102
#define IDC_DREFUSE                     1105
#define IDC_DACCEPT                     1106
#define IDC_ALLOWSHUTDOWN               1107
#define IDC_ALLOWEDITCLIENTS            1108
#define IDC_NEW_MSLOGON                 1109
#define IDC_HIDE_B                      1110
#define IDC_FTUSERIMPERSONATION_CHECK   1117
#define IDC_REMOVE_Aero                 1118
#define IDE_CUSTOM1                     1119
#define IDC_WWW2                        1120
#define IDC_WWW3                        1121
#define IDC_CHECK1                      1122
#define IDC_JAP_INPUTS                  1122
#define IDC_CHECK3                      1123
#define IDC_EURO                        1123
#define IDC_RDPMODE                     1123
#define IDC_VIDEO                       1125
#define IDC_BUTTON1                     1126
#define IDC_CLEAR                       1126
#define IDC_CONNECTION_NUMBER_LABEL     1128
#define IDC_CONNECTION_NUMBER_STATIC    1128
#define IDC_CAPTION_STATIC              1129
#define IDC_ACCEPTLOGO                  1131
#define IDC_Path1                       1132
#define IDC_CHECK4                      1132
#define IDC_IPV6                        1132
#define IDC_Path2                       1133
#define IDC_Path3                       1134
#define IDC_LOCALTEXT_EDIT              1140
#define IDC_INPUTAREA_EDIT              1140
#define IDC_REMOTETEXT_EDIT             1141
#define IDC_CHATAREA_EDIT               1141
#define IDC_CLEAR_B                     1142
#define IDC_FINGER                      9000
#define IDC_GAMMAGRAY                   9001
#define IDC_STATIC_SPLIT                9002
#define ID_ADMIN_PROPERTIES             40000
#define ID_PROPERTIES                   40001
#define ID_CLOSE                        40002
#define ID_KILLCLIENTS                  40003
#define ID_ABOUT                        40004
#define ID_OUTGOING_CONN                40005
#define ID_DEFAULT_PROPERTIES           40006
#define ID_LISTCLIENTS                  40007
#define ID_ONLINEHELP                   40013
#define ID_HOME                         40014
#define ID_CLOSE_SERVICE                40015
#define ID_RUNASSERVICE                 40016
#define ID_UNINSTALL_SERVICE            40017
#define ID_START_SERVICE                40018
#define ID_TRAY_VISITUSONLINE           40019
#define ID_VISITUSONLINE_HOMEPAGE       40020
#define ID_VISITUSONLINE_FORUM          40021
#define ID_TRAY_ENABLESOFTWARECAD       40022
#define ID_SOFTWARECAD                  40023
#define ID_TRAY_REBOOTINSAFEMODE        40024
#define ID_REBOOTSAFEMODE               40025
#define ID_TRAY_DELETESOFTWARECAD       40026
#define ID_DELSOFTWARECAD               40027
#define ID_TRAY_FORCEREBOOT             40028
#define ID_REBOOT_FORCE                 40029
#define ID_FAILED_INIT                  41000
#define ID_WINVNC_USAGE                 41001
#define ID_ANOTHER_INST                 41002
#define ID_NO_EXIST_INST                41003
#define ID_UNABLE_INST                  41004
#define ID_SCM_NOT_HERE                 41005
#define ID_SERV_NOT_REG                 41006
#define ID_SERV_FAIL_ST                 41007
#define ID_SERV_CT_MISS                 41008
#define ID_SERV_OLD_REG                 41009
#define ID_SERVHELP_UNAB                41010
#define ID_SERV_CT_UNREG                41011
#define ID_SERV_NOT_UNRG                41012
#define ID_SERV_NCONTACT                41013
#define ID_SERVHELP_NREM                41014
#define ID_SERV_NOT_STOP                41015
#define ID_SERV_MK_UNREG                41016
#define ID_SERV_NT_FOUND                41017
#define ID_WINVNC_ERROR                 41018
#define ID_WINVNC_WARNIN                41019
#define ID_PLUGIN_LOADIN                41020
#define ID_NO_PASSWD_NO_OVERRIDE_ERR    41021
#define ID_NO_PASSWD_NO_OVERRIDE_WARN   41022
#define ID_NO_PASSWD_NO_LOGON_WARN      41023
#define ID_NO_OVERRIDE_ERR              41024
#define ID_NO_CURRENT_USER_ERR          41025
#define ID_CANNOT_EDIT_DEFAULT_PREFS    41026
#define ID_NO_PASSWORD_WARN             41027
#define ID_PLUGIN_NOT_LOAD              41028
#define ID_MB1                          41029
#define ID_WVNC                         41030
#define ID_AUTHAD_NOT_FO                41031
#define ID_WARNING                      41032
#define ID_AUTH_NOT_FO                  41033
#define ID_DESKTOP_BITBLT_ROOT          41034
#define ID_DESKTOP_BITBLT_MEM           41035
#define ID_DESKTOP_PLANAR_NOTC          41036
#define ID_FAILED_CONNECT_LISTING_VIEW  41037
#define ID_OUTGOING_CONNECTION          41038
#define ID_UNABLE_PROC_MSLOGON          41039
#define ID_RICHED32_UNLOAD              41040
#define ID_RICHED32_DLL_LD              41041
#define ID_SERV_SUCCESS_INST            41042
#define ID_SERV_SUCCESS_REG             41043
#define ID_SERV_SUCCESS_UNREG           41044
#define ID_ULTRAVNC_TEXTCHAT            41045
#define ID_ULTRAVNC_WARNING             41046
#define ID_NO_PLUGIN_DETECT             41047
#define ID_CHAT_WITH_S_ULTRAVNC         41048
#define ID_CURRENT_USER_PROP            41049
#define ID_DEFAULT_SYST_PROP            41050
#define ID_AUTOREJECT_U                 41051
#define ID_AUTOACCEPT_U                 41052
#define ID_CADERROR                     41053
#define ID_CADERRORFILE                 41054
#define ID_CADPERMISSION                41055

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        170
#define _APS_NEXT_COMMAND_VALUE         40030
#define _APS_NEXT_CONTROL_VALUE         1133
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
