.\"                                      Hey, EMACS: -*- nroff -*-
.\" First parameter, NAME, should be all caps
.\" Second parameter, SECTION, should be 1-8, maybe w/ subsection
.\" other parameters are allowed: see man(7), man(1)
.TH VEYON-SERVICE 1 2013-08-12 Veyon
.\" Please adjust this date whenever revising the manpage.
.\"
.\" Some roff macros, for reference:
.\" .nh        disable hyphenation
.\" .hy        enable hyphenation
.\" .ad l      left justify
.\" .ad b      justify to both left and right margins
.\" .nf        disable filling
.\" .fi        enable filling
.\" .br        insert line break
.\" .sp <n>    insert n+1 empty lines
.\" for manpage-specific macros, see man(7)
.SH NAME
veyon-service \- Veyon Service Application
.SH SYNOPSIS
.B veyon-service
.br
.SH DESCRIPTION
.PP
.\" TeX users may be more comfortable with the \fB<whatever>\fP and
.\" \fI<whatever>\fP escape sequences to invode bold face and italics, 
.\" respectively.
.B VEYON-SERVICE
is the software which needs to run on student computers in order to access them using Veyon Master. It provides a VNC server and a service daemon which is necessary for taking control over the computer.
.PP
.SH SEE ALSO
.IR veyon-master (1), veyon-configurator (8), veyon-auth-helper (1)
.PP
.IR http://veyon.io/

.SH AUTHOR
Veyon has been written by Tobias Junghans.
.PP
This manual page has been written by Tobias Junghans and updated by Mike Gabriel. It was originally written for the Debian project (but may be used by others).
