.\"                                      Hey, EMACS: -*- nroff -*-
.\" First parameter, NAME, should be all caps
.\" Second parameter, SECTION, should be 1-8, maybe w/ subsection
.\" other parameters are allowed: see man(7), man(1)
.TH ITALC 1 "February 1, 2008"
.SH NAME
italc \- iTALC Master Application
.SH SYNOPSIS
.B italc
.SH DESCRIPTION
.B iTALC
is the actual software to control iTALC-clients. Using it's GUI you can remote-control, lock, shutdown/reboot computers as well as show a demo, send text-messages to users and much more.
.
.SH OPTIONS
.IP "\fB\-rctrl\fP \fIhost:[port]\fP
.IP
Directly remote-control the specified host. You can omit port if the server is running at the default-port (11100).
.
.IP "\fB\-isdport\fP \fIport\fP
.IP
Set port to which iTALC should connect in order to contact the local iTALC-service-daemon. Default: 11200
.
.IP "\fB\-isdhost\fP \fIip\fP
.IP
Set the host to which iTALC should connect in order to contact the local iTALC-service-daemon. Default: localhost
.
.PP
.SH SEE ALSO
.IR ica (1),
.IR http://italc.sf.net
.SH AUTHOR
iTALC was written by Tobias Doerffel. See AUTHORS for details.
.PP
This manual page was written by Steffen Joeris <steffen.joeris@skolelinux.de>
and Tobias Doerffel <tobydox /at/ users /dot/ sf /dot/ net>, for the Debian project (but may be used by others).
