.\"                                      Hey, EMACS: -*- nroff -*-
.\" First parameter, NAME, should be all caps
.\" Second parameter, SECTION, should be 1-8, maybe w/ subsection
.\" other parameters are allowed: see man(7), man(1)
.TH ITALC 1 "November  20, 2005"
.SH NAME
italc \- iTALC Master Application
.SH SYNOPSIS
.B italc
.SH DESCRIPTION
.B italc
makes it possible, to access and influence the pupils
activities just from the computer of the teacher. With the
help of iTALC, for example the teacher is able to see the
content of the pupils screens on his screen. If a pupil needs
help, the teacher can access the pupils desktop and give support
from his computer. The pupil can watch all activities, the
teacher is doing on his desktop. So the pupil can learn new processes.
For teaching something to all pupils, you can switch into demo-mode
where all screens of the pupils show the teacher-screen.
Furthermore things like locking pupil's screens, killing games,
power on/off clients and much more can be done with iTALC.
.PP
.SH SEE ALSO
.IR ica (1),
.IR http://italc.sf.net
.SH AUTHOR
iTALC was written by Tobias Doerffel. See AUTHORS for details.
.PP
This manual page was written by Steffen Joeris <steffen.joeris@skolelinux.de>,
for the Debian project (but may be used by others).
