.\"                                      Hey, EMACS: -*- nroff -*-
.\" First parameter, NAME, should be all caps
.\" Second parameter, SECTION, should be 1-8, maybe w/ subsection
.\" other parameters are allowed: see man(7), man(1)
.TH VEYON-SERVER 1 2018-12-07 Veyon
.\" Please adjust this date whenever revising the manpage.
.\"
.\" Some roff macros, for reference:
.\" .nh        disable hyphenation
.\" .hy        enable hyphenation
.\" .ad l      left justify
.\" .ad b      justify to both left and right margins
.\" .nf        disable filling
.\" .fi        enable filling
.\" .br        insert line break
.\" .sp <n>    insert n+1 empty lines
.\" for manpage-specific macros, see man(7)
.SH NAME
veyon-server \- Veyon Server
.SH SYNOPSIS
.B veyon-server
.br
.SH DESCRIPTION
.PP
.\" TeX users may be more comfortable with the \fB<whatever>\fP and
.\" \fI<whatever>\fP escape sequences to invode bold face and italics,
.\" respectively.
\fBVEYON-SERVER\fR is a server application which provides access to a
computer as well as control and application functions.
.PP
Under normal conditions this program is started by the Veyon Service
automatically and with elevated privileges so it can’t be terminated by
users.
.PP
.SH SEE ALSO
veyon-service(1), veyon-master(1), veyon-configurator(8), veyon-auth-helper(1)
.PP
https://veyon.io/

.SH AUTHOR
Veyon has been written by Tobias Junghans.
.PP
This manual page has been written by Tobias Junghans and Mike Gabriel. It
was originally written for the Debian project (but may be used by
others).
