.\"                                      Hey, EMACS: -*- nroff -*-
.\" First parameter, NAME, should be all caps
.\" Second parameter, SECTION, should be 1-8, maybe w/ subsection
.\" other parameters are allowed: see man(7), man(1)
.TH VEYON MASTER 1 2018-12-07 Veyon
.SH NAME
veyon-master \- Veyon Master Application
.SH SYNOPSIS
.B veyon-master
.SH DESCRIPTION
\fBVEYON MASTER\fR is an application program that can be used for
monitoring and controlling other computers as well as for accessing Veyon
features.
.PP
Usually the program is started by the end user. It accesses other
computers through the Veyon Service.
.PP
Using the program you can remote control, lock, shutdown/reboot computers
as well as show a demo, send text messages to users and much more.

.SH SEE ALSO
veyon-service(1), veyon-configurator(8), veyon-auth-helper(1)
.PP
https://veyon.io

.SH AUTHOR
Veyon has been written by Tobias Junghans.
.PP
This manual page has been written by Tobias Junghans and Mike Gabriel. It
was originally written for the Debian project (but may be used by
others).
