FROM opensuse:42.2
MAINTAINER Tobias Doerffel <tobias.doerffel@gmail.com>

RUN \
	zypper install -y git gcc6-c++ make cmake rpm-build \
		libqt5-qtbase-devel libqt5-linguist-devel libqt5-qttools-devel \
		libXtst-devel libXrandr-devel libXinerama-devel \
		libjpeg8-devel \
		zlib-devel \
		libpng16-devel \
		libopenssl-devel \
		pam-devel lzo-devel \
		libqca-qt5-devel libqca-qt5-plugins \
		openldap2-devel cyrus-sasl-devel

