.TH VEYON-CONFIGURATOR 1 2018-12-07 Veyon
.SH NAME
veyon-configurator \- Veyon Configurator
.SH SYNOPSIS
\fBveyon-configurator\fP
.SH DESCRIPTION

\fBVEYON-CONFIGURATOR\fR is a configuration tool which allows the site
admin to configure and customize all components of a local Veyon
installation through a graphical user interface. The program is started
by the administrator with elevated privileges whenever necessary.

.PP
For more information about the veyon-configurator, point your browser to file:///usr/share/doc/packages/veyon-configurator or http://veyon.io/.
.SH SEE ALSO
.IR veyon-service (1), veyon-master (1)

.PP
.IR http://veyon.io/

.SH AUTHOR
Veyon has been written by Tobias Junghans.
.PP
This manual page has been written by Frank Schütte and updated by Tobias Junghans.
