# BuildApplication.cmake - Copyright (c) 2019-2020 Tobias Junghans
#
# description: build Veyon application
# usage: BUILD_APPLICATION(<NAME> <SOURCES>)

MACRO(BUILD_APPLICATION APPLICATION_NAME)
	SET(APPLICATION_SOURCES ${ARGN})

	IF(VEYON_BUILD_ANDROID)
		ADD_LIBRARY(${APPLICATION_NAME} SHARED ${APPLICATION_SOURCES})
	ELSE()
		ADD_EXECUTABLE(${APPLICATION_NAME} ${APPLICATION_SOURCES})
		INSTALL(TARGETS ${APPLICATION_NAME} RUNTIME DESTINATION bin)
	ENDIF()
ENDMACRO()

