MACRO(CONFIGURE_FILES)
	FOREACH(f ${ARGN})
		STRING(REPLACE ".in" "" OUT_FILE "${f}")
		CONFIGURE_FILE(${CMAKE_CURRENT_SOURCE_DIR}/${f} ${CMAKE_CURRENT_BINARY_DIR}/${OUT_FILE} @ONLY)
	ENDFOREACH(f ${IN_FILES})
ENDMACRO()

