include(cotire)
macro(cotire_veyon TARGET_NAME)
	if(WITH_PCH AND NOT VEYON_DEBUG)
		get_target_property(_targetType ${TARGET_NAME} TYPE)
		if(NOT VEYON_BUILD_ANDROID OR NOT _targetType STREQUAL "EXECUTABLE")
			set_target_properties(${TARGET_NAME} PROPERTIES COTIRE_CXX_PREFIX_HEADER_INIT "${PROJECT_SOURCE_DIR}/core/src/Cotire.h")
			cotire(${TARGET_NAME})
		endif()
	endif()
endmacro()
