include(cotire)
macro(COTIRE_VEYON TARGET_NAME)
get_target_property(_targetType ${TARGET_NAME} TYPE)
if(NOT VEYON_DEBUG)
if(NOT VEYON_BUILD_ANDROID OR NOT _targetType STREQUAL "EXECUTABLE")
set_target_properties(${TARGET_NAME} PROPERTIES COTIRE_CXX_PREFIX_HEADER_INIT "${PROJECT_SOURCE_DIR}/core/src/Cotire.h")
cotire(${TARGET_NAME})
endif()
endif()
endmacro()
