MACRO(SET_DEFAULT_TARGET_PROPERTIES TARGET_NAME)
	SET_PROPERTY(TARGET ${TARGET_NAME} PROPERTY CXX_STANDARD 14)
	SET_PROPERTY(TARGET ${TARGET_NAME} PROPERTY CXX_STANDARD_REQUIRED ON)
	IF(NOT DISABLE_LTO AND NOT VEYON_DEBUG)
	SET_TARGET_PROPERTIES(${TARGET_NAME} PROPERTIES INTERPROCEDURAL_OPTIMIZATION TRUE)
	ENDIF()
ENDMACRO()

