FROM fedora:26
MAINTAINER Tobias Doerffel <tobias.doerffel@gmail.com>

RUN \
	yum install -y git gcc-c++ make cmake rpm-build \
		qt5-qtbase-devel qt5-qtbase qt5-linguist qt5-qttools \
		libXtst-devel libXrandr-devel libXinerama-devel \
		libjpeg-turbo-devel \
		zlib-devel \
		libpng-devel \
		openssl-devel \
		pam-devel \
		lzo-devel \
		qca-qt5-devel qca-qt5-ossl \
		openldap-devel
